spring.application.name=fraud-detection
spring.datasource.url=jdbc:mysql://localhost:3306/fraud_detection
spring.datasource.username=root
spring.datasource.password=qkqz9kws

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect